FROM mysql:5.7

MAINTAINER "tolikzuzin.com@gmail.com"

ENV MYSQL_ROOT_PASSWORD="tolik228root"

ENV MYSQL_DATABASE="Zuzin"

ENV MYSQL_USER="zuzin228"

ENV MYSQL_PASSWORD="tolik228"

RUN mysql

EXPOSE 3306
